### ISSUE TITLE
make install does nothing

### ISSUE THREAD

**Issue by napseis** [Auburn/FastNoise2#10]
Hello,
I discovered your program this week, and it's working really nice, thank you.
 I'm using it directly in a C++ code, so I have to link the libraries.

The only probem is, the install target seems broken. 
My cmake command is `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..`
When I run "make install", with a custom install prefix or not, nothing happens, just:

```
[  9%] Built target FastNoise
[  9%] Built target MagnumShaders_RCS-dependencies
[ 16%] Built target CorradeUtilityObjects
[ 22%] Built target CorradeUtility
[ 25%] Built target corrade-rc
[ 28%] Built target MagnumShadersObjects
[ 32%] Built target MagnumMathObjects
[ 36%] Built target MagnumObjects
[ 42%] Built target Magnum
[ 69%] Built target MagnumGLObjects
[ 70%] Built target MagnumFlextGLObjects
[ 78%] Built target MagnumGL
[ 84%] Built target MagnumShaders
[ 89%] Built target MagnumImGuiIntegration
[ 90%] Built target MagnumGlxContextObjects
[ 92%] Built target MagnumPlatformObjects
[ 93%] Built target MagnumSdl2Application
[ 93%] Built target MagnumSceneGraphObjects
[ 96%] Built target MagnumSceneGraph
[100%] Built target NoiseTool
Install the project...
-- Install configuration: "Release"
```
So right now I just copy manually the include folder, and the `build/Release/lib` ,`build/Release/bin` folders, but it's not very efficient.
Am I doing something wrong ? I didn't see any install target in the CMakeLists.txt, but  didn't fiddle too much...

Thank you

**Comment by Auburn** [comment]
This is my first project using CMake so I'm still figuring stuff out. I haven't setup anything for install, I'm not really sure what that entails.

**Comment by napseis** [comment]
Ha ok, so it is expected behavior. I do a bit of cmake myself, so I tried, and if i add

```
install(TARGETS NoiseTool FastNoise
        LIBRARY DESTINATION lib
        RUNTIME DESTINATION bin)
```
in the end of `NoiseTool/CMakeLists.txt`, it seems to work.
i don't really know how to deal with the includes though, it should be an argument of install,`PUBLIC_HEADER DESTINATION include`,  where you define your headers.

thanks anyway !
