### ISSUE TITLE
[Question] What is the output range of your Simplex Noise implementation

### ISSUE THREAD

**Issue by harald921** [Auburn/FastNoise2#101]
Hello!

As the title suggests, I wonder what the output range of an FBm using Simplex Noise is.

I have not been able to find answers for these things in the documentation, but if the information already is there then I apologize.

Fantastic library, by the way!

**Comment by Auburn** [comment]
Coherent noise nodes are bound -1 : 1 the same applies when using them in a fractal. The only exception to this is cellular noise
