### ISSUE TITLE
Getting RGBA8 texture

### ISSUE THREAD

**Issue by samthesuperhero** [Auburn/FastNoise2#104]
Hello everybody,

can't understand how can I get usual RGBA8 data from the generator.

All generators output floats.

Documentation does not exist.

There is FastNoise::ConvertRGBA8 but it has float output.

Convert RGBA8 in NoiseTool GUI as well shows something veeery strange.

Can you please help & in future document it at least somehow ??

**Comment by Auburn** [comment]
If you case the output of ConvertRGBA8 from `float*` to `uint8*` you will have the correct format. The noisetool does this internally for all the texture previews if you want a reference.

I'm currently working on better docs, I know it is lacking.

**Comment by samthesuperhero** [comment]
Great, works, thank you much!!
