### ISSUE TITLE
GenUniformGrid2D only returning 0.

### ISSUE THREAD

**Issue by The-Brandolorian** [Auburn/FastNoise2#106]
I'm currently using this function to troubleshoot the outputs, I'm in UE5.1 using the plugin to import the library.
The position passed in is the actors world position, generating 3D noise works as expected however 2D noise does not.
Currently it is only returning 0.00000 for each index in the float vector, furthermore while messing around earlier sometimes the return would include results well out of the bounds of -1 to 1 (5-8 digit numbers and if i recall correctly even some that returned INF??).
Its probably an user error but maybe you could point me in the right direction, cheers!

void AChunk::GenerateNoise(const FVector Position)
{
	Density.reserve(ChunkSize);
	Continent.reserve(ChunkSize);

	DensityNoiseGenerator->GenUniformGrid3D(Density.data(), Position.X, Position.Y, Position.Z, Size, Size, ChunkHeight, 
        DensityFrequency, Seed);

	ContinentNoiseGenerator->GenUniformGrid2D(Continent.data(), Position.X, Position.Y, Size, Size, ContinentFrequency, Seed);

	for (int i = 0; i < Continent.size() - 1; ++i) // Im aware this throws an out of bounds error, was a quick and dirty debug.
	{
		UE_LOG(LogTemp, Warning, TEXT("Value : %f"), Continent[i]); // If Continent changed to Density, returns results as expected.
	}
}

**Comment by Auburn** [comment]
If that is a std::vector you should be using resize instead of reserve,
that might be the cause of the issue.

**Comment by The-Brandolorian** [comment]
It in fact is, oops. what an overlook.. Cheers!
However, It still returns 0 at each index.

I realised I should probably include more information, this is my noise setup:

        //Density
        DensityNoiseGenerator = FastNoise::New<FastNoise::FractalFBm>();
	DensityNoiseGenerator->SetSource(FastNoise::New<FastNoise::Perlin>());
	DensityNoiseGenerator->SetGain(0.3f);
	DensityNoiseGenerator->SetLacunarity(2.0f);
	DensityNoiseGenerator->SetOctaveCount(4);

	//Continent
	ContinentNoiseGenerator = FastNoise::New<FastNoise::FractalFBm>();
	ContinentNoiseGenerator->SetSource(FastNoise::New<FastNoise::Perlin>());
	ContinentNoiseGenerator->SetGain(0.5);
	ContinentNoiseGenerator->SetLacunarity(2.5f);
	ContinentNoiseGenerator->SetOctaveCount(4);

Declarations:

        FastNoise::SmartNode<FastNoise::FractalFBm> DensityNoiseGenerator;
	FastNoise::SmartNode<FastNoise::FractalFBm> ContinentNoiseGenerator;
        std::vector<float> Density;
        std::vector<float> Continent;

**Comment by The-Brandolorian** [comment]
And as posting this I think I fixed it, I was resizing it to the size a 3 Dimensional grid and changing it to resize for Size * Size appears to have worked.

Strange that having the vector be larger than needed was causing the values to not be updated, but thanks for your reply anyway!
