### ISSUE TITLE
PositionOutput repeating on GenUniformGrid2D 

### ISSUE THREAD

**Issue by Optimoos** [Auburn/FastNoise2#107]
I'm not sure if this is me misunderstanding how PositionOutput should work or if something is actually going wrong. In the NoiseTool, a simple PositionOutput with X=3.0 produces a single horizontal line:

![image](https://user-images.githubusercontent.com/1445030/210661077-20c4fc76-fcd0-45d2-a257-9f8306d508c5.png)

When I do this myself, I get these repeating lines: 

![image](https://user-images.githubusercontent.com/1445030/210661379-d7e4e6db-063a-4fc9-a8a2-49b6716b4c32.png)

This is where I'm not sure whether it's my expectations going awry. I'm using GenUniformGrid2D to supply starting locations and size to generate 256x256 chunks of noise. All the other generators I've used (OpenSimplex2, FractalFBm, DomainScale at least) have produced the tiling effect as expected and have matched what I've configured in the noise tool. Some output of multiple generators combined that looks fine to me:

![image](https://user-images.githubusercontent.com/1445030/210662753-9d2aa22e-0ff0-4f61-8d9d-1a59ea46be3f.png)

I looked through PositionOutput code but am still learning and wasn't able to follow the templates and inlining.

**Comment by Auburn** [comment]
Can you show how you are calling `GenUniformGrid2D`?

**Comment by Optimoos** [comment]
`
    auto fnGenerator = FastNoise::New<FastNoise::PositionOutput>();
    fnGenerator->Set<FastNoise::Dim::Y>(3.0f, 0.0f);
    uint16_t y_tile_count = 0;
    uint16_t x_tile_count = 0;
    worldtiles.resize(WORLD_Y/worldtile::TILE_Y);
    for (std::vector<worldtile>& x_tiles : worldtiles) {
        x_tiles.resize(WORLD_X/worldtile::TILE_X);
        for (worldtile& tile : x_tiles) {
            tile.blocks.resize(worldtile::TILE_X * worldtile::TILE_Y);

            fnGenerator->GenUniformGrid2D(tile.blocks.data(),
                                        x_tile_count * worldtile::TILE_X,
                                        y_tile_count * worldtile::TILE_Y,
                                        worldtile::TILE_X,
                                        worldtile::TILE_Y,
                                        0.02f, 1337);
            x_tile_count++;
        }
        y_tile_count++;
        x_tile_count = 0;
    }`

Let me know if more context is needed.

**Comment by Auburn** [comment]
That code looks correct, not sure where it's going wrong...
