### ISSUE TITLE
How to install this library?

### ISSUE THREAD

**Issue by Volper212** [Auburn/FastNoise2#11]
I tried copying the include folder to my project but then when I do `#include "FastNoise/FastNoise.h"` I get the error:

```
fatal error: 'FastSIMD/FastSIMD.h' file not found
```
It's something about directories, it's trying to find the `FastSIMD` folder inside the `FastNoise` folder instead of where I include the file. How do I make it work without adding `../` everywhere in the header files? If I move the `FastSIMD` folder inside the `FastNoise` folder I get more errors about files not being found, and manually editing your files looks more like a workaround instead of a solution

BTW I see you use CMake, do I need to use it to be able to use your library? I literally never used CMake and I don't know how it works

**Comment by caseymcc** [comment]
You need a bit more info in order to help you with this, OS and build environment mainly. You can hit the discord https://discord.gg/SHVaVfV for faster feed back.

**Comment by Volper212** [comment]
OK i will make my issue on Discord

**Comment by Volper212** [comment]
Ok solution is on Discord on text channel fastnoise2

**Comment by caseymcc** [comment]
Documented on the wiki now.

https://github.com/Auburn/FastNoise2/wiki/Compiling-FastNoise
