### ISSUE TITLE
View zoom in Node Editor

### ISSUE THREAD

**Issue by samthesuperhero** [Auburn/FastNoise2#111]
Dear contributors,

any ideas how to zoom in / out in Node Editor ?

Thank you much, really cool tool !

**Comment by Auburn** [comment]
There is a PR for support of this in the node editor library I am using, https://github.com/Nelarius/imnodes/pull/134

**Comment by samthesuperhero** [comment]
It's not merged, you mean one can just apply the patch and build the whole stuff from soruce?

**Comment by samthesuperhero** [comment]
Clear, thx!
