### ISSUE TITLE
Compile on macOS ARM doesn't produce binary

### ISSUE THREAD

**Issue by andraghetti** [Auburn/FastNoise2#114]
Hi! Thank you so much for this tool!

I was trying to compile the tool, but it doesn't produce anything in the `build/bin` directory.

I'm running `cmake -S . -B build -D FASTNOISE2_NOISETOOL=ON -D FASTNOISE2_TESTS=ON -D BUILD_SHARED_LIBS=ON`.

Output: [result.txt](https://github.com/Auburn/FastNoise2/files/11582375/result.txt)
cmake version 3.26.4

**Comment by Auburn** [comment]
That command will generate the build files, to then actually run the build you need to follow the next steps in the wiki, https://github.com/Auburn/FastNoise2/wiki/1:-Compiling-FastNoise2#cmake-build

**Comment by andraghetti** [comment]
Oh my bad! Thank you so much :) I'm not used to cmake. It works perfectly! Thank you!
