### ISSUE TITLE
Is there C bindings?

### ISSUE THREAD

**Issue by xzores** [Auburn/FastNoise2#118]
Is there C bindings? and how does one do it?

And if not could there be C bindings?

:)

**Comment by Auburn** [comment]
The C bindings are here: https://github.com/Auburn/FastNoise2/blob/master/include/FastNoise/FastNoise_C.h

**Comment by xzores** [comment]
perfect, thanks for the clarification

**Comment by xzores** [comment]
Could you clarify if these bindings use the SIMD version or not?

**Comment by Auburn** [comment]
Yeah, it will automatically use the highest supported SIMD feature set the
same as in C++
