### ISSUE TITLE
periodic noise(s)

### ISSUE THREAD

**Issue by unicomp21** [Auburn/FastNoise2#12]
Especially on the cellular side of things, is there a way to generate tiled/toroidal 3D volumes of noise?

https://github.com/aqsis/aqsis/blob/883cc9e027108d596437e231f6d05ef01d0cdda8/libs/math/noise1234.cpp#L325

**Comment by Auburn** [comment]
It's possible for 2D using 4D noise, but there are currently no plans to add the 6D noise required for tiled 3D noise. Certain noise types will get periodic versions that could be used, it's on the to-do list.

**Comment by unicomp21** [comment]
@Auburn to be honest, I don't understand how 6D noise can be used to tile 3D noise.  Is there a link somewhere explaining how this is done?  Or some way for me to get my head around it?

**Comment by unicomp21** [comment]
Maybe if I understood how to tile 2D noise using 4D noise, I could generalize from there.

**Comment by Auburn** [comment]
If you imagine a 1D line could be made to loop by drawing a circle in 2D, that is basically what happens for each dimension. 1 dimension is moved to 2 dimensions using sin and cos

**Comment by unicomp21** [comment]
Thansk @Auburn!
