### ISSUE TITLE
What do I use the voxel tool for?

### ISSUE THREAD

**Issue by xzores** [Auburn/FastNoise2#120]
What do I use the graph tool for? Can I save my work and load the node graph it in my game?

Also I would really like to see a more complex remap (Like a curve remap, as shown here).
![th-1883081294](https://github.com/Auburn/FastNoise2/assets/17770917/46606d2c-60aa-4cce-92e8-4e8d971fa976)

**Comment by Auburn** [comment]
You can export a node tree from the NoiseTool by right clicking on the node. The encoded node tree can then be loaded in your own code using `FastNoise::NewFromEncodedNodeTree()`
