### ISSUE TITLE
DistanceToPoint NaN at (0,0)

### ISSUE THREAD

**Issue by ccudahy** [Auburn/FastNoise2#124]
The DistanceToPoint generator using Euclidean distance produces a NaN at (0,0).  Note the single white pixel in the center:
![image](https://github.com/Auburn/FastNoise2/assets/2526622/4e397cff-c329-4efd-8fcd-cd9b210575b0)

I've tracked this down to CalcDistance() which is using the fast approximate reciprocal square root function, instead of the slower(?) sqrt. When the distance is zero, (1/sqrt(d)) * d produces NaN.

There seems to be a few ways to address this, with various pros and cons:
1) The obvious is to switch to sqrt. This fixes the NaN, but in my rough testing the node is about 10-20% slower. This is fine for my application, but maybe not idea for others?
2) Various internet posts suggest dealing with NaNs by detecting them in various ways (test distSqr==0, or result=result) and then masking to replace with zero. This fixes the NaN at (0,0), but still leaves an area (very) near (0,0) as Inf or NaN. If you zoom with the texture preview (a lot!) you can see this - note the correct black pixel in the center, with the white NaN/Inf doughnut:
![image](https://github.com/Auburn/FastNoise2/assets/2526622/1ef79307-c181-448e-923a-2fa810d0f400)
3) Instead, testing for < float32v( FLT_MAX ) detects both, and seems to produce correct output.
```
                    float32v unmasked = FS_InvSqrt_f32( distSqr ) * distSqr;
                    float32v dist = FS_Mask_f32( unmasked, unmasked < float32v( FLT_MAX ) );
                    return dist;
```
4) Use a small empirically derived epsilon and call it a day. This works as far as I can see.
```
                    float32v unmasked = FS_InvSqrt_f32( distSqr ) * distSqr;
                    float32v dist = FS_Mask_f32( unmasked, distSqr > float32v( 0.00000000001 ) );
                    return dist;
```

If any of the above is desired I can make a small PR?

**Comment by Auburn** [comment]
Thanks for looking at this, I had noticed it before but not gotten around to fixing it.

I think 3 is probably the best solution but use `MaskedMul`. Also comparing vs +inf might be better than flt_max, if it also works.

**Comment by ccudahy** [comment]
I was just putting together a PR, but looks like you beat me to the fix, and found another instance as well.

Your test is different than the one I was considering, and I'm surprised it is working since I would have expected that (NaN != Infinity)==true.  Maybe the invSqrt is not making NaNs where I thought, just Inf?

Anyway, thanks for the great library!
