### ISSUE TITLE
API Documentation / best place to search for in source code

### ISSUE THREAD

**Issue by bogdan-brz** [Auburn/FastNoise2#125]
Hello, I can't find any documentation of the API or any working code examples. Do you know where I could find something? or could you point me to which part of the source code I should go through to understand the API better?
Thank you.

**Comment by Auburn** [comment]
There is a short getting started guide with examples in the wiki

https://github.com/Auburn/FastNoise2/wiki/3:-Getting-started-using-FastNoise2
