### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by unicomp21** [Auburn/FastNoise2#13]
Can we get an emscripten build as well?  Which leverages webassembly simd in chrome?

**Comment by Auburn** [comment]
I have looked into this briefly, last I checked emscripten didn't support all the required SIMD operations. Arm support would be a priority before this anyway.

**Comment by jijjijj** [comment]
@Auburn it [seems](https://emscripten.org/docs/porting/simd.html) Emscripten supports most of the SIMD modes FastSIMD supports:
```
#define FASTSIMD_COMPILE_SSE    (FASTSIMD_x86 & false) // Not supported, wasm check
#define FASTSIMD_COMPILE_SSE2   (FASTSIMD_x86 & true ) // wasm check
#define FASTSIMD_COMPILE_SSE3   (FASTSIMD_x86 & true ) // wasm check
#define FASTSIMD_COMPILE_SSSE3  (FASTSIMD_x86 & true ) // wasm check
#define FASTSIMD_COMPILE_SSE41  (FASTSIMD_x86 & true ) // wasm check
#define FASTSIMD_COMPILE_SSE42  (FASTSIMD_x86 & true ) // wasm check
#define FASTSIMD_COMPILE_AVX    (FASTSIMD_x86 & false) // Not supported, wasm check
#define FASTSIMD_COMPILE_AVX2   (FASTSIMD_x86 & true ) // No support in wasm
#define FASTSIMD_COMPILE_AVX512 (FASTSIMD_x86 & true ) // No support in wasm
```

So would it be theoretically feasible to add at least some SIMD support for emscripten/wasm?
