### ISSUE TITLE
Some Iffy Implementation in Unreal 5.4 (Or a Skill Issue on my part)

### ISSUE THREAD

**Issue by TemptressLuna** [Auburn/FastNoise2#137]
First off, I recognize that I may trying to put a square peg into a round hole here, but I'd like to start off by saying that I was able to get the library accessible in my source code using the UE4CMake guide. The issue I'm facing are the following linker warnings: 

[LinkerWarnings.txt](https://github.com/user-attachments/files/16516486/LinkerWarnings.txt)

Which occurs when I put this "auto noise = FastNoise::New<FastNoise::Simplex>();" into my code. Now, I'm still figuring out how to utilize this effectively, so I apologize if I've made some kind of cardinal sin or done something stupid, but I've tried modifying one of the files with some guidance from AI reading the warnings and it (unsurprisingly) only made things worse.

I'm using a built "Release" of the repo downloaded 8/5/2024 and am using Unreal 5.4. If this is out of your scope, I understand, but if there's any guidance (or 'fixes'/changes that may help the repo) you can give me on addressing these warnings and reducing risk of runtime instability down the line I'd appreciate it. Apologies for any faux pas, I've never submitted an issue on here before.

**Comment by Auburn** [comment]
The linker error suggest you aren't linking against the FastNoise.lib

**Comment by TemptressLuna** [comment]
Ohmygosh, I fixed it, thank you. I had `CMakeTarget.add(Target, this, "FastNoise", FastNoise2Path, "-DFASTNOISE2_NOISETOOL=OFF", true);` instead of `CMakeTarget.add(Target, this, "FastNoise2", FastNoise2Path, "-DFASTNOISE2_NOISETOOL=OFF", true);`. You're amazing Auburn, love your work, ty!

**Comment by Auburn** [comment]
I'm not sure how UECMake works, might need some guidance from @caseymcc
