### ISSUE TITLE
Unexpected results from position output node when using GenUniformGrid3D

### ISSUE THREAD

**Issue by pinecone69** [Auburn/FastNoise2#141]
I am using a position output node with one dimension set like this:

`fnPos->Set<FastNoise::Dim::Z>(1.f, -256.f);
`

And with all other dimensions set to (0, 0).

So the multiplier is 1 and offset is -256 for the Z dimension.

When using GenUniformGrid3D to generate a grid with the range for example (0, 512) on all axes, it seems no noise values generated are positive.

My understanding is that the position output node's output is (input position + offset) * multiplier, so this seems to produce unexpected results when using GenUniformGrid3D. All noise values with Z coordinates above 256 should be positive, and all below should be negative. This is demonstrable when using GenSingle3D to generate a value above Z = 256 and then below that.

Here is some code to test this:

```
static auto fnPos = FastNoise::New<FastNoise::PositionOutput>();

fnPos->Set<FastNoise::Dim::X>(0.f, 0.f);
fnPos->Set<FastNoise::Dim::Y>(0.f, 0.f);
fnPos->Set<FastNoise::Dim::Z>(1.f, -256.f);

float test1 = fnPos->GenSingle3D(0.f, 0.f, 257.f, 1337); // Should be positive
float test2 = fnPos->GenSingle3D(0.f, 0.f, 255.f, 1337); // Should be negative

const unsigned SIZE = 512;
const unsigned SIZE_CUBED = SIZE * SIZE * SIZE;
float* noiseTest = new float[SIZE_CUBED];

fnPos->GenUniformGrid3D(noiseTest, 0, 0, 0, SIZE, SIZE, SIZE, 0.02f, 1337);

for (uint32_t i = 0; i < SIZE_CUBED; i++) {
    if (noiseTest[i] > 0.f) {
        std::cout << "positive\n";
    }
}
```

My assumption is that all position values for GenUniformGrid3D would be on a range from (iStart, iStart + iSize) with i being whatever dimension. Please help me if I am mistaken.

**Comment by pinecone69** [comment]
`float* noiseTest = new float[SIZE];`

Should be 

`float* noiseTest = new float[SIZE_CUBED];`

**Comment by Auburn** [comment]
When using `GenUniformGrid3D` all the positions are multiplied by the frequency before being passed to any node. 
I'm changing this behaviour in the 1.0 release due to confusions like this.

**Comment by pinecone69** [comment]
Okay, multiplying the desired threshold by the frequency solves this behavior.
