### ISSUE TITLE
Crash that doesn't trigger exception with g++ with wingw but not with msvc

### ISSUE THREAD

**Issue by IlaPoly** [Auburn/FastNoise2#142]
When creating a SmartNode in code using the app like so :

`FastNoise::SmartNode<> fnGenerator = FastNoise::NewFromEncodedNodeTree("EQACAAAAAAAgQBAAAAAAQBkAEwCamRk/DQAEAAAAAAAgQAkAAAAAAD8AAAAAAAEEAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM3MTD4AmpkZPwAAAAAA");`

And then generating a 3d or 2d noise like so :

`fnGenerator->GenUniformGrid3D(noiseOutput.data(), 0, 0, 0, Chunk::length, Chunk::length, Chunk::length, 0.2f, 1337);`

The program crash exactly at this line if I build my program using mingw build with g++, but not if I build with msvc. I can't even catch an exception with mingw or make it crash with msvc.

This doesn't happen when using : ` auto fnSimplex = FastNoise::New<FastNoise::Simplex>();` and then generating noise.

Although when using this method it sometimes crashes with mingw with no explanation but doesn't do it all the time...

**Comment by Auburn** [comment]
See #69
