### ISSUE TITLE
histogram preview

### ISSUE THREAD

**Issue by malytomas** [Auburn/FastNoise2#16]
Would it be possible to add histogram preview that would show content corresponding to the texture preview?

As an example, I want to match terrain levels with this:
https://commons.wikimedia.org/wiki/File:Earth_elevation_histogram.svg
(the histogram should have swapped axes)

**Comment by Auburn** [comment]
That wouldn't really make sense for the noise tool since it works with more abstract concepts of noise in a volume. There is no 0 height, there isn't even a "terrain" unless you use some modifiers

**Comment by malytomas** [comment]
I guess you misunderstood my example, but the concept is much widely applicable.

Generally, I want to generate noise output that has specific distribution. Sometimes, I want constant - black is equally as common as white and equally as common as gray. Other times I want black to occupy 80%, gray 15% and white 5%. Sometimes I want logarithmic curve. And so on and so forth.

If the 2D texture was used as heightmap, it is a terrain, and Earths terrain has some specific distribution which can be achieved with the nodes. Its just that having histogram would make it significantly simpler to _reason about designing the nodes graph_. I do not mean it as output, that would make little sense of course.

If you really see histogram unfit, than at least consider showing minimum and maximum values. Among other things, it would have hinted at the issue with checkerboard used in the fade node #15.

**Comment by Auburn** [comment]
ok I think I understand what you mean now. There is a min/max for the 3D preview, I would like to add it for the 2D preview too it's not as easy though since the conversion into a texture happens inside FastNoise. I've been trying to think of a good way to work around this without too big of a performance hit, when I do I can also look at adding a histogram as well.
