### ISSUE TITLE
XY start for tileable 2D noise?

### ISSUE THREAD

**Issue by chaoticbob** [Auburn/FastNoise2#20]
Been using this in a framework for some experimental stuff, love the ease of use! 

Was wondering if it's possible to have a xStart and yStart for tileable 2D noise or is it impossible?

**Comment by Auburn** [comment]
What purpose do you want to achieve by setting x/yStart. I don't think it will have the affect you think it will. It would be possible to offset the 4D noise used to generate 2D tileable but changing the seed would have a very similar effect.

**Comment by chaoticbob** [comment]
There's a few case I have where it would be convenient to offset xStart so that edge values are at specific place for a given seed. I realize it's possible to do with changing the seed but it's not as predictable. I also get that this can be done post noise generation just by shifting sampling position as well. If it doesn't seem useful to have than I'll just do that.

**Comment by Auburn** [comment]
2D tileable is generated using 4D noise so the edges wouldn't match up to 2D noise generation.

**Comment by chaoticbob** [comment]
Got it. Thanks.
