### ISSUE TITLE
Missing copy or save for the node tree

### ISSUE THREAD

**Issue by Miirpat-Gaalsien** [Auburn/FastNoise2#33]
I hope it's just the fact that I'm running version 0.7 on Linux/X11, but I found no way to copy or save the encoded node tree.

So far I attempted:
- Ctrl + C
- Select and right click
- Right clicking the node, the text box, the subwindow for a save option
- Repeating everything with the windows version through wine

**Comment by Auburn** [comment]
This is an issue with ImGui not natively supporting clipboard on linux, it's on my list to look at. There is a temp fix to add a button to the UI to print out the encoded node tree, but it's not in the latest release

**Comment by Miirpat-Gaalsien** [comment]
My mistake, it took me a while to figure out how to checkout git submodules, the dump to CLI button appeared after I compiled
