### ISSUE TITLE
FastNoise::OperatorSourceLHS::SetRHS': ambiguous call to overloaded function

### ISSUE THREAD

**Issue by Groenbech96** [Auburn/FastNoise2#35]
Im currently building using cpp 20 and visual studio 2019.
When I try to use a generator as RHS input on a OperatorSourceLHS, the compiler can decide what function overload to use.

Am i using the library incorrecly?

![image](https://user-images.githubusercontent.com/17690329/113557399-3d714f80-95fe-11eb-9d56-b0ac694e3a96.png)

**Comment by Auburn** [comment]
Hi, it was an error in the interface of the new SmartNode type I added recently. I've fixed it in: https://github.com/Auburn/FastNoise2/commit/deb8c464890b3af136144ebb227a4f3bad616c09
