### ISSUE TITLE
Implicit conversion from `const uint64_t` to `size_t` for `SmartNodeManager::kInvalidReferenceId`

### ISSUE THREAD

**Issue by JayFoxRox** [Auburn/FastNoise2#42]
Compiling for a 32-bit platform with a custom clang toolchain; I get this:

```
FastNoise2/include/FastNoise/SmartNode.h:240:28: warning: implicit conversion from 'const uint64_t' (aka 'const unsigned long long') to 'size_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Wconstant-conversion]
            mReferenceId = SmartNodeManager::kInvalidReferenceId;
                         ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Problem originates here:

https://github.com/Auburn/FastNoise2/blob/1f7dc6aae1cef6174d54ec8889cd5122adf61f5b/include/FastNoise/SmartNode.h#L16

However, most of the code assumes `uint64_t`, so I assume the fix will be to change the following  to `uint64_t mReferenceId;`:

https://github.com/Auburn/FastNoise2/blob/1f7dc6aae1cef6174d54ec8889cd5122adf61f5b/include/FastNoise/SmartNode.h#L264

Looks like this was forgotten here: https://github.com/Auburn/FastNoise2/commit/be585cd51ddbd917d18bd727297889728bfa5af8 - another instance probably exists here (which should also be using `uint64_t` now):

https://github.com/Auburn/FastNoise2/blob/1f7dc6aae1cef6174d54ec8889cd5122adf61f5b/include/FastNoise/SmartNode.h#L255

**Comment by Auburn** [comment]
Looking at this more it seems to only be an issue with the DomainWarpFractalProgressive node, and as far as I can tell it's an MSVC compiler bug that only occurs on 32bit release builds...

**Comment by caseymcc** [comment]
You should be using size_t for the id in the first place (rather than uint64_t). That way it will change to native size for 32 and 64 bit systems.

**Comment by Auburn** [comment]
It stores 2x uint32_t values so it shouldn't be a size_t

**Comment by caseymcc** [comment]
Didn't dig through the implementation, thought it was just a reference index for the most part. Packing 2 unsigned shorts for the 32bit version might be beneficial but really who cares about optimizing for 32bit :)
