### ISSUE TITLE
error LNK2019: unresolved external symbol "__declspec(dllimport) .....

### ISSUE THREAD

**Issue by Simon-R-IT** [Auburn/FastNoise2#49]
I have been unable to link the lib when compiling from source in VS2019. I get 2 unresolved externals due to the "__declspec(dllimport)" when compiling my own project

Full output : 

> error LNK2019: unresolved external symbol "__declspec(dllimport) private: static void __cdecl FastNoise::SmartNodeManager::DecReference(unsigned __int64,void *,void (__cdecl*)(void *))" (__imp_?DecReference@SmartNodeManager@FastNoise@@CAX_KPEAXP6AX1@Z@Z) referenced in function "private: void __cdecl FastNoise::SmartNode<class FastNoise::Generator>::Release(void)" (?Release@?$SmartNode@VGenerator@FastNoise@@@FastNoise@@AEAAXXZ)
> 
> error LNK2019: unresolved external symbol "__declspec(dllimport) class FastNoise::SmartNode<class FastNoise::Generator> __cdecl FastNoise::NewFromEncodedNodeTree(char const *,enum FastSIMD::eLevel)" (__imp_?NewFromEncodedNodeTree@FastNoise@@YA?AV?$SmartNode@VGenerator@FastNoise@@@1@PEBDW4eLevel@FastSIMD@@@Z) referenced in function "private: __cdecl RoP::WorldGen::WorldGen(void)" (??0WorldGen@RoP@@AEAA@XZ)

I'm probably doing something wrong, but if I'm getting this error, I'm sure someone else also will at some point.

Cheers

**Comment by pinecone69** [comment]
I'm also getting this error. Auburn doesn't explicitly say how to link the library using visual studio.

**Comment by Auburn** [comment]
Are you compiling the FastNoise 2 source your self or using the pre compiled binaries from one of the releases?

**Comment by pinecone69** [comment]
> Are you compiling the FastNoise 2 source your self or using the pre compiled binaries from one of the releases?

I've tried both and still get linker errors. If you want I can go into further detail on how I compiled FastNoise 2 and/or used the pre compiled binaries.

**Comment by Auburn** [comment]
You should be linking to FastNoise.lib in your visual studio project. Also make sure you are using the headers from the same FastNoise 2 version as the lib file was built using

**Comment by pinecone69** [comment]
> You should be linking to FastNoise.lib in your visual studio project. Also make sure you are using the headers from the same FastNoise 2 version as the lib file was built using

I'm using Unreal Engine 4 and following their examples on how to link third party libraries. After I have compiled FastNoise2 I linked FastNoise.lib to my project and have added include paths for the headers - the same version as the library. There must be something else?

**Comment by caseymcc** [comment]
Added info on including the lib, https://github.com/Auburn/FastNoise2/wiki/Including-the-library-in-your-project.

**Comment by connorjak** [comment]
I was able to resolve this myself in this way:
```c++
// FastNoise_Config.h
-#define FASTNOISE_USE_SHARED_PTR false
+#define FASTNOISE_USE_SHARED_PTR true
```

```c++
// The only place I #include FastNoise
#define FASTNOISE_STATIC_LIB
#include <FastNoise/FastNoise.h>
```

**Comment by caseymcc** [comment]
@connorjak was your link errors the same as above?

Its likely better to link as a static lib since the plugin for UE4  will already be a dll.

**Comment by connorjak** [comment]
Yes exactly the same errors
