### ISSUE TITLE
No debug lib in release zip.

### ISSUE THREAD

**Issue by caseymcc** [Auburn/FastNoise2#50]
@Auburn there is no debug version of the lib in the release package. You should include the FastNoised.lib (and FastNoised.dll) as well. This might cause the issue seen here (https://github.com/Auburn/FastNoise2/issues/49) but likely not, normally it causes other kinds of linking problems related to std lib/etc...

**Comment by Auburn** [comment]
Is a debug version of the DLL also needed or not?

**Comment by caseymcc** [comment]
Yeah, it is what will be searched for when using the FastNoised.lib

**Comment by Auburn** [comment]
Fixed with https://github.com/Auburn/FastNoise2/commit/ecfd618594d08b185feeb371bee0c7d41ad4ce02
