### ISSUE TITLE
Wiki images

### ISSUE THREAD

**Issue by caseymcc** [Auburn/FastNoise2#51]
![image](https://user-images.githubusercontent.com/2903823/123139848-406d2680-d41c-11eb-823f-2b0a4eb28eb5.png)
![image](https://user-images.githubusercontent.com/2903823/123141772-5b409a80-d41e-11eb-819b-98eef5a6953f.png)
![image](https://user-images.githubusercontent.com/2903823/123140096-86c28580-d41c-11eb-842e-590141402a82.png)
![image](https://user-images.githubusercontent.com/2903823/123141030-8d053180-d41d-11eb-841c-4a6fc6bfc211.png)

**Comment by Auburn** [comment]
Did GitHub not add wiki page support for pasting images directly when they added support for .md files?

**Comment by caseymcc** [comment]
Apparently not for the wiki, I tried but would not work,
