### ISSUE TITLE
[Feature Request] Make it possible to see values for the bounds of the generated mesh preview in the editor, or some other way to see "height" of terrain

### ISSUE THREAD

**Issue by echush** [Auburn/FastNoise2#57]
When using FastNoise2 for generating terrain, it would be very useful to see values for the "height" of the generated terrain. 

Example: Say you import the "Simple Terrain" template in the editor. You see a terrain. The terrain has a pretty consistent "height" (distance between lowest point and highest point) everywhere, and the overall height can most easily be adjusted by changing the "Y multiplier" in the "Position Output" node. But the absolute value of the height is not really possible to see. Let's say you want to use this output as an actual landscape in your software, and you know that your software has a landscape height limit of 1000 "voxels". Either for technical reasons, or maybe in the case of a game also for gameplay reasons. It would be extremely useful then if you could already see in the FastNoise2 editor what the actual "height" of that output is so that you can tweak the output to be most useful for your usecase in your software.

In the case of the mesh preview in the FastNoise2 editor, that "height" would be the distance in blocks between the lowest  Y coordinate of a block, and the highest Y coordinate of a block (Y is up/down in the editor, right?). Of course, some people might not generate such "horizontal" terrain as in the "Simple Terrain" case, so seeing values for all axis would be very useful, not just "height". In the case of the "Simple Terrain" template, the height axis would give you a value of around 30 voxels or so, and "infinite" in the other 2 axis.

The bounds could either be based on the min/max of the generated mesh preview, or it could instead display the "theoretical" min/max based on the nodes, in most cases, it should be roughly same, so doesn't really matter which way it's calculated.

**Comment by echush** [comment]
@Auburn Do you think this is possible? Or is there maybe some way already now to see those values?

**Comment by Auburn** [comment]
There is no way to get the theoretical min/max directly from the node tree, it would need to be something more rudimentary like the min/max y vert position from the meshes

**Comment by echush** [comment]
Ok, then it would be best to display the min/max coordinate each for X/Y/Z of the mesh. I assume that's probably easy to implement?

**Comment by douglasg14b** [comment]
I have a request that's similar to knowing the output bounds, normalizing.

I have a need to normalize the output, ensuring it's clamped between 0 and 1. I'm trying to replace my own noise generation code, where I pre-calculate the global max & min, and then normalize my output to be between 0 and 1.

Is there a way to do this with a node? I was messing around with the `remap` one, with little success.

**Comment by douglasg14b** [comment]
For reference this is how I currently normalize my noise:

```cs
private static void Normalize(float[] noiseArr, float minHeight, float maxHeight, float lowerBound, float upperBound)
{
	for(int i = 0; i < noiseArr.Length; i++)
    {
		float normalized = Maths.InverseLerp(minHeight, maxHeight, noiseArr[i]);

		if (normalized < lowerBound)
		{
			normalized = 0;
		}
		else if (normalized > upperBound)
		{
			normalized = 1;
		}

		noiseArr[i] = Maths.InverseLerp(lowerBound, upperBound, normalized);
	}
}
```

**Comment by Auburn** [comment]
I've added a min air Y and max solid Y for the voxel mesh: https://github.com/Auburn/FastNoise2/commit/a228926dcaf0491ea18c7221834e2b9590958d3c

Calculating the theoretical min/max for a node tree would be quite a lot of work to add. I think in a lot of cases it wouldn't even be that useful since it would be very far off from the actual output in many cases.
