### ISSUE TITLE
[Feature Request] Make it possible to see performance cost of the node network and ideally how much which nodes contribute to that cost

### ISSUE THREAD

**Issue by echush** [Auburn/FastNoise2#58]
When creating a node network in FastNoise2, it would be extremely useful to see the performance cost of the whole node network, and how which nodes are contributing to the total performance cost of the noise.

As an example, take the "Simple Terrain" template. If I look at the node network, then the most obvious cost that I can indentify is obviously the 4 octaves of OpenSimplex2 noise. The "Domain Scale" I assume is pretty much free, the "Position Output" is probably also pretty much free, the "Add" node probably too. But after that, it becomes way more difficult to judge. I don't know how much the "Domain Warp Gradient" affects the performance cost. The work it's doing is more complex than a simple add, but probably also way less than 4 octaves of simplex noise, so I would assume, it's also relatively cheap, but I can't know. It would be great to know exaxt values for that. And the last node, "Domain Warp Fractal" is most difficult to judge. It itself adds 2 octaves, so it's probably quite expensive, but how expensive exactly? 

I would like to be able to immedietaly see what the performance difference is between using 4 Octaves in the "Fractal FBm" node and 2 Octaves in the "Domain Warp Fractal" node, vs using 3 Octaves in the "Fractal FBm" node and 2 Octaves in the "Domain Warp Fractal" node. Currently, I have no idea if that makes any difference at all, if it's same expensive, if one is way more expensive than the other, how I should tweak the values to end up with something that both looks good and is as efficient as possible.

Even just seeing a "total cost" for the whole node network would help a lot, as then it could easily be figured out with A/B testing how much which node affects the performance. It should probably be very easy for the mesh preview to calculate the "nanoseconds per voxel" or something similar? Or just the total generation time for the "Texture Preview".

**Comment by Auburn** [comment]
Yes, this is on my to-do list. I think each node can have a total and delta generation cost, although it would be 2D costs. Can maybe add an option for 3D previews to solve that too

**Comment by echush** [comment]
Nice!

**Comment by echush** [comment]
@Auburn while the node editor does not show it yet, is there maybe any rough documentation anywhere about how expensive some of the often used nodes are, or is the only way to know that currently by profiling different noise configs manually in my own code? I'm especially interested in how much performance impact a "Domain Warp Gradient" has, how "Fractal Ridged" compares to "Fractal FBM", and how "Simplex" compares to "Open Simplex 2".

**Comment by Auburn** [comment]
Here are the performance charts that get updated with every commit: https://auburn.github.io/fastnoise2benchmarking/

I should probably link them somewhere 😅

**Comment by echush** [comment]
That's very useful charts, thanks! That would be very useful to have linked in the readme and documentation.

**Comment by Auburn** [comment]
I have added performance counters to the node graph https://github.com/Auburn/FastNoise2/commit/cfce4d807c8aa07c37b1e5d54445a811ba67a614

The results are quite noisy though so take them with a grain of salt

**Comment by echush** [comment]
Thanks!
