### ISSUE TITLE
'NewFromEncodedNodeTree' results in an error in an Unreal Engine plugin

### ISSUE THREAD

**Issue by RoyWheels** [Auburn/FastNoise2#65]
Thank you for this lovely bit of noise fun. It's a nice system.

I have had success in making a simple UE5 plugin containing the FastNoise.lib (built using cmake without the noisetool) and the folders of includes (FastNoise and FastSIMD). However, there is one issue.

I can use all the noise features apart from 'NewFromEncodedNodeTree' . If I try and implement it I'll get the following error on building:

`  unresolved external symbol "__declspec(dllimport) private: static void __cdecl FastNoise::SmartNodeManager::DecReference(unsigned __int64,void *,void (__cdecl*)(void *))" (__imp_?DecReference@SmartNodeManager@FastNoise@@CAX_KPEAXP6AX1@Z@Z) referenced in function "public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)`

`  unresolved external symbol "__declspec(dllimport) class FastNoise::SmartNode<class FastNoise::Generator> __cdecl FastNoise::NewFromEncodedNodeTree(char const *,enum FastSIMD::eLevel)" (__imp_?NewFromEncodedNodeTree@FastNoise@@YA?AV?$SmartNode@VGenerator@FastNoise@@@1@PEBDW4eLevel@FastSIMD@@@Z) referenced in function "public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)`

` 2 unresolved externals`

Do the '2 unresolved externals' possibly refer to missing files related to the noisetool? I'm still thinking it's an error that I've created but after staring at the code for a couple of days I'm feeling a bit lost.

**Comment by Auburn** [comment]
It looks like FastNoise.lib is not being included in the linking stage of the build. That code is not related to the noise tool. I'm not familiar with the UE5 build config but it looks like you are missing the library linking stage

**Comment by RoyWheels** [comment]
Would you have an idea as to why everything else is working? That's the bit that confuses me. I can use FastNoise2 with the other noise construction method of adding params line by line. It's only the newfromencodednodetree function that fails.

**Comment by Auburn** [comment]
I don't see how anything would work if it can't resolve "FastNoise::SmartNodeManager::DecReference"

Are you using the code in a different place than you had the FastNoise2 code working before?

**Comment by RoyWheels** [comment]
I've been making sure I clean out any trace of older versions/caches as I go. 

I've had a little, probably not very useful, progress. If I initialise a noise stream using the other 'New<FastNoise::Simplex>()' method whilst also starting a newfromencodednodetree stream, the nodetree output will work.

I can then run the project (it's a simple marching cubes thing) and see the results of using the nodegenerated stream. I do however get a few warnings when it builds.

The warnings :

`symbol '?GetLastAllocID@SmartNodeManager@FastNoise@@CA_KPEAX@Z (private: static unsigned __int64 __cdecl FastNoise::SmartNodeManager::GetLastAllocID(void *))' defined in 'FastNoise.lib(SmartNode.obj)' is imported by 'DrawMarchingCubes.cpp.obj' in function '"public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)'

symbol '?IncReference@SmartNodeManager@FastNoise@@CAX_K@Z (private: static void __cdecl FastNoise::SmartNodeManager::IncReference(unsigned __int64))' defined in 'FastNoise.lib(SmartNode.obj)' is imported by 'DrawMarchingCubes.cpp.obj' in function '"public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)'

symbol '?DecReference@SmartNodeManager@FastNoise@@CAX_KPEAXP6AX1@Z@Z (private: static void __cdecl FastNoise::SmartNodeManager::DecReference(unsigned __int64,void *,void (__cdecl*)(void *)))' defined in 'FastNoise.lib(SmartNode.obj)' is imported by 'DrawMarchingCubes.cpp.obj' in function '"public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)'

symbol '?DecReference@SmartNodeManager@FastNoise@@CAX_KPEAXP6AX1@Z@Z (private: static void __cdecl FastNoise::SmartNodeManager::DecReference(unsigned __int64,void *,void (__cdecl*)(void *)))' defined in 'FastNoise.lib(SmartNode.obj)' is imported by 'DrawMarchingCubes.gen.cpp.obj'

symbol '?Allocate@SmartNodeManager@FastNoise@@CAPEAX_K0@Z (private: static void * __cdecl FastNoise::SmartNodeManager::Allocate(unsigned __int64,unsigned __int64))' defined in 'FastNoise.lib(SmartNode.obj)' is imported by 'DrawMarchingCubes.cpp.obj' in function '"public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)'

symbol '?NewFromEncodedNodeTree@FastNoise@@YA?AV?$SmartNode@VGenerator@FastNoise@@@1@PEBDW4eLevel@FastSIMD@@@Z (class FastNoise::SmartNode<class FastNoise::Generator> __cdecl FastNoise::NewFromEncodedNodeTree(char const *,enum FastSIMD::eLevel))' defined in 'FastNoise.lib(Metadata.obj)' is imported by 'DrawMarchingCubes.cpp.obj' in function '"public: __cdecl ADrawMarchingCubes::ADrawMarchingCubes(void)" (??0ADrawMarchingCubes@@QEAA@XZ)'`

I'll keep investigating. Thank you for the help so far.

**Comment by Auburn** [comment]
Have you tried using the pre compiled library and headers from the latest release instead of using your own built versions?

**Comment by RoyWheels** [comment]
I've tried with the last x64 release and can get the plugin mounted but UE5 crashes if I try and implement some noise. I'll keep looking into it. 

Just having my not quite right janky working version has been great. I love the noise tool and simple copy paste into code!

**Comment by Auburn** [comment]
Make sure you use the headers provided with the binaries, mismatching header and binary versions will cause it to crash on boot
