### ISSUE TITLE
Performance comparison with FastNoiseSIMD in readme

### ISSUE THREAD

**Issue by echush** [Auburn/FastNoise2#66]
It would be useful if the readme would also include FastNoiseSIMD in the performance comparison table, currently it only has "FastNoise Lite", "FastNoise (Legacy)" and "FastNoise2 (AVX2)", but no "FastNoiseSIMD (AVX2)". 

I'm interested in knowing if there have been any significant performance improvements between FastNoiseSIMD and FastNoise2 that would make updating an existing codebase from FastNoiseSIMD to FastNoise2 worth it.

**Comment by Auburn** [comment]
Here is where the original data come from for those tables, it has FastNoiseSIMD values. https://docs.google.com/spreadsheets/d/1f_ldJeuYvOjc_MxbzNKcURLDcvKIt1L2TuC--Kme-7w/edit?usp=drivesdk

Compare using the median, items per second values

**Comment by echush** [comment]
Thanks for that table, that's good to have.

I assume the FastNoiseSIMD values in that table are AVX2, and the table does not contain any AVX512 comparisons?

So for 3D Simplex noise, FastNoiseSIMD AVX2 can do 199.90 "Million points of noise generated per second", and FastNoise2 AVX2 268.44. That's a significant improvement, nice.

**Comment by Auburn** [comment]
They are AVX2 numbers, you can run the AVX512 numbers yourself if you have a CPU that supports it. Here is the benchmark tool I made, https://github.com/Auburn/NoiseBenchmarking
