### ISSUE TITLE
Cannot paste into Encoded Node Tree text field

### ISSUE THREAD

**Issue by douglasg14b** [Auburn/FastNoise2#67]
In the node editor, I'm unable to paste into the field at the top.

I assume we can paste into this field, but Ctrl+V doesn't do anything. Ctrl+C will copy it's contents though.

System: Windows 10
Release:  v0.8.2-alpha

![image](https://user-images.githubusercontent.com/1400380/129494801-e8d1f6e9-8e48-4137-b988-a67faac6f10e.png)

**Comment by Auburn** [comment]
That is a read-only field, you can import an encoded node tree from the add nodes menu
![image](https://user-images.githubusercontent.com/1349548/129496304-280a69bd-49e3-4712-b34a-5afd7ac17c6b.png)
