### ISSUE TITLE
Release FastNoise2-v0.9.0 carsh while use any node

### ISSUE THREAD

**Issue by lybmccree** [Auburn/FastNoise2#70]
v0.8.2-alpha work fine

**Comment by Auburn** [comment]
Can you provide more details?

**Comment by lybmccree** [comment]
win10
intel i5-10400 
GTX1050TI

**Comment by Auburn** [comment]
Where in your code does the crash occur?
Or is it when using the NoiseTool?

**Comment by lybmccree** [comment]
> Where in your code does the crash occur?
> Or is it when using the NoiseTool?
I dont know how to complie the code 
I just download newest Release windows version.  
click FBM
![image](https://user-images.githubusercontent.com/42838946/133588185-82dedfb1-aa21-476c-99eb-1645a0ee9f05.png)

**Comment by Auburn** [comment]
The crash does not happen for me when running in 0.9.0 NoiseTool in the releases

Could you compile NoiseTool and reproduce the crash to see where the issue is occurring?

There is a guide on compiling here: https://github.com/Auburn/FastNoise2/wiki/1:-Compiling-FastNoise2

**Comment by lybmccree** [comment]
> The crash does not happen for me when running in 0.9.0 NoiseTool in the releases
> 
> Could you compile NoiseTool and reproduce the crash to see where the issue is occurring?
> 
> There is a guide on compiling here: https://github.com/Auburn/FastNoise2/wiki/1:-Compiling-FastNoise2

OK, I have a try, I install CMake just now

**Comment by lybmccree** [comment]
I dont know how to use cmake , I use vs2019 open cmake project ,and..don't kown how to complie

**Comment by lybmccree** [comment]
what's the cmake version or vs verion can open and complie this project

**Comment by Auburn** [comment]
Any CMake version above 3.12 will work, you can open the CMake project directly with VS2019 if you have the CMake support installed for VS

**Comment by lybmccree** [comment]
it notice error
FastNoise2-master\NoiseTool\CMakeLists.txt:1 (CPMAddPackage):
Unknown CMake command "CPMAddPackage".FastNoise2-master\NoiseTool\CMakeLists.txt	1

**Comment by Auburn** [comment]
You need to open the `FastNoise2-master\` folder as CMake project not `FastNoise2-master\NoiseTool\`

**Comment by lybmccree** [comment]
It can't complie faild
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
1> [CMake]   cpm-cache/magnum/4a29e9de94e887479a7414f8904b07061e08415f/modules/FindCorrade.cmake:304 (find_package_handle_standard_args)
1> [CMake]   cpm-cache/magnum/4a29e9de94e887479a7414f8904b07061e08415f/CMakeLists.txt:59 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "D:/Mydemo/Noise/FN_Sources/FastNoise2-master/out/build/x86-MSVC-Debug/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "D:/Mydemo/Noise/FN_Sources/FastNoise2-master/out/build/x86-MSVC-Debug/CMakeFiles/CMakeError.log".
1> “C:\windows\system32\cmd.exe”“/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\out\install\x86-MSVC-Debug" -DCPM_SOURCE_CACHE:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\cpm-cache" -DFASTNOISE2_TESTS:BOOL="True" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x86/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x86/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\Mydemo\Noise\FN_Sources\FastNoise2-master" 2>&1"”执行失败，出现错误:““C:\windows\system32\cmd.exe”“/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\out\install\x86-MSVC-Debug" -DCPM_SOURCE_CACHE:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\cpm-cache" -DFASTNOISE2_TESTS:BOOL="True" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x86/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x86/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\Mydemo\Noise\FN_Sources\FastNoise2-master" 2>&1"”已返回，并带有退出代码: 1”。

**Comment by lybmccree** [comment]
0. 0 can you send me a VS  project? my env is not right;
email is 443874716@qq.com

**Comment by Auburn** [comment]
Can you send the full output, the error is not included in the section you sent

**Comment by Auburn** [comment]
I cannot send you a pregenerated VS solution since it doesn't use relative paths when generating it, so it would not work for you anyway

**Comment by lybmccree** [comment]
已为配置“x64-MSVC-Debug”启动 CMake 生成。
1> CMakeSettings "addressSanitizerEnabled" 值与 CMAKE_C_FLAGS or CMAKE_CXX_FLAGS 不一致。
1> 环境设置:
1>     CXXFLAGS=-fsanitize=address
1>     CFLAGS=-fsanitize=address
1> 命令行: "C:\windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\out\install\x64-MSVC-Debug" -DCPM_SOURCE_CACHE:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\cpm-cache" -DFASTNOISE2_TESTS:BOOL="True" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\Mydemo\Noise\FN_Sources\FastNoise2-master" 2>&1"
1> 工作目录: D:\Mydemo\Noise\FN_Sources\FastNoise2-master\out\build\x64-MSVC-Debug
1> [CMake] -- The C compiler identification is MSVC 19.29.30038.1
1> [CMake] -- The CXX compiler identification is MSVC 19.29.30038.1
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - failed
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe - broken
1> [CMake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
1> [CMake]   The C compiler
1> [CMake] 
1> [CMake]     "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe"
1> [CMake] 
1> [CMake]   is not able to compile a simple test program.
1> [CMake] 
1> [CMake]   It fails with the following output:
1> [CMake] 
1> [CMake]     Change Dir: D:/Mydemo/Noise/FN_Sources/FastNoise2-master/out/build/x64-MSVC-Debug/CMakeFiles/CMakeTmp
1> [CMake]     
1> [CMake]     Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_58ab7 && [1/2] Building C object CMakeFiles\cmTC_58ab7.dir\testCCompiler.c.obj
1> [CMake]     [2/2] Linking C executable cmTC_58ab7.exe
1> [CMake]     FAILED: cmTC_58ab7.exe 
1> [CMake]     cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_58ab7.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_58ab7.dir\testCCompiler.c.obj  /out:cmTC_58ab7.exe /implib:cmTC_58ab7.lib /pdb:cmTC_58ab7.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
1> [CMake]     LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_58ab7.dir\testCCompiler.c.obj /out:cmTC_58ab7.exe /implib:cmTC_58ab7.lib /pdb:cmTC_58ab7.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_58ab7.dir/intermediate.manifest CMakeFiles\cmTC_58ab7.dir/manifest.res" failed (exit code 1104) with the following output:
1> [CMake]     LINK : fatal error LNK1104: 无法打开文件“clang_rt.asan_dbg_dynamic-x86_64.lib”
1> [CMake]     ninja: build stopped: subcommand failed.
1> [CMake]     
1> [CMake]     
1> [CMake] 
1> [CMake]   
1> [CMake] 
1> [CMake]   CMake will not be able to correctly generate this project.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:4 (project)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "D:/Mydemo/Noise/FN_Sources/FastNoise2-master/out/build/x64-MSVC-Debug/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "D:/Mydemo/Noise/FN_Sources/FastNoise2-master/out/build/x64-MSVC-Debug/CMakeFiles/CMakeError.log".
1> “C:\windows\system32\cmd.exe”“/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\out\install\x64-MSVC-Debug" -DCPM_SOURCE_CACHE:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\cpm-cache" -DFASTNOISE2_TESTS:BOOL="True" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\Mydemo\Noise\FN_Sources\FastNoise2-master" 2>&1"”执行失败，出现错误:““C:\windows\system32\cmd.exe”“/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\out\install\x64-MSVC-Debug" -DCPM_SOURCE_CACHE:PATH="D:\Mydemo\Noise\FN_Sources\FastNoise2-master\cpm-cache" -DFASTNOISE2_TESTS:BOOL="True" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx86/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\Mydemo\Noise\FN_Sources\FastNoise2-master" 2>&1"”已返回，并带有退出代码: 1”。

**Comment by Auburn** [comment]
>1> [CMake] -- Detecting C compiler ABI info - failed
>1> [CMake] is not able to compile a simple test program.

This is the error, it is unrelated FastNoise

Here is a debug build of NoiseTool. If you attach to the process in VS before causing the crash you should be able to save the crash dump in VS and send it back to me.
[NoiseToolDebug.zip](https://github.com/Auburn/FastNoise2/files/7185252/NoiseToolDebug.zip)
