### ISSUE TITLE
How can I make 2D terrain generation "move" without using a bigger 2D array?

### ISSUE THREAD

**Issue by tugrul512bit** [Auburn/FastNoise2#74]
With following method call,

```
fnGenerator->GenUniformGrid2D((float *)heightmap, 0, 0, mapSize, mapSize, 0.2f, 1337);
```

it generates a static map but what if I need to move the noise pattern itself 1 cell left or 1 cell up without changing heightmap size? Is there some offset option like using scalar FastNoiseLite method calls? With FastNoiseLite, this was working:

```
 heightmap[i][j]=noise.GetNoise((float)(j+translationx), (float)(i+translationy));
```

with bumping each noise point by translationx and translationy.

**Comment by Auburn** [comment]
Use the `xStart` and `yStart` arguments in the `GenUniform2D` function, they are set to 0 in your example
