### ISSUE TITLE
DomainScale : Gui vs API inconsistencies

### ISSUE THREAD

**Issue by avillani** [Auburn/FastNoise2#76]
hi,
I'm trying to replicate in C++ what I do in the GUI:
- Generate Simplex
- apply fractal fbm with varying parameters
- apply domain scale, with value around 1. (0.95 to 1.05 for instance)

In the GUI, the domain scale is applied from the center, it zooms on the image like a homothety, which is exactly what i want. But I cannot replicate this behavior in C++, the SetScale function has no other parameter than the scale.
Here is basically what I do: 

```cpp
for (auto sd = seed_range.begin(); sd < seed_range.end(); sd++) {

    // FastNoise::New inside because I was doing generation in parallel
    
    auto fnFractal_ = FastNoise::New<FastNoise::FractalFBm>();  
    fnNoise = FastNoise::New<FastNoise::Simplex>();
    fnFractal_->SetSource(fnNoise);
    auto fnFractal = FastNoise::New<FastNoise::DomainScale>();
    fnFractal->SetSource(fnFractal_);
    
    for (auto const &o: octave_range) {
        for (auto const &g: gain_range) {
            for (auto const &l: lacunarity_range) {
            
                std::fill(data.begin(), data.end(), 0);
                fnFractal_->SetOctaveCount(o);
                fnFractal_->SetGain(g);
                fnFractal_->SetLacunarity(l);
                fnFractal->SetScale(1);
                
                fnFractal->GenUniformGrid2D(data.data(), 0, 0, img_size, img_size, 0.02, *sd); 
                //fnFractal->GenTileable2D(data.data(), img_size, img_size, 0.02, *sd);
                 
                for (auto const &k : k_range) {
                    std::fill(data.begin(), data.end(), 0);
                    fnFractal->SetScale(k);
                    fnFractal->GenUniformGrid2D(data.data(), 0, 0, img_size, img_size, 0.02, *sd);
                    //fnFractal->GenTileable2D(data.data(), img_size, img_size, 0.02, *sd);
                }
            }
        }
    }
}
```
With GenUniformGrid2D, it seems to scales ok, but from the top left corner of the image, not from the center.
Now I could do it in opencv, but I'd have to pad and fill, etc, and it seems silly since it should be easy in FastNoise from what i see.
(Also and more importantly, I'm hoping the scale is computed early in the process, hopefully analytically, and is not an image transformation.)

Please, am I missing something ?

Thank you

**Comment by Auburn** [comment]
In NoiseTool the previews have the origin at the centre of the texture preview. You can mimic this by setting the start positions to be half the axis length, like this:
`fnFractal->GenUniformGrid2D(data.data(), -img_size / 2, -img_size / 2, img_size, img_size, 0.02, *sd);`

**Comment by avillani** [comment]
I'm an idiot, I tried with  `+img_size / 2`
Thank you !
