### ISSUE TITLE
Mac osx precompiled doesn't have any executable files

### ISSUE THREAD

**Issue by slit-bodmod** [Auburn/FastNoise2#77]
Hi I went to the releases section looking for a version of NoiseTool I could run on my mac. I downloaded a file called  FastNoise2-v0.9.4-alpha-MacOS64-Clang.zip and tried to work out how I could launch it but there was no file in there that seemed to be executable or that would start the application, I tried downloading the windows version and that contained an exe but when I tried to run that on my work computer it said that it was missing a dll file, am I being dumb and not launching the program correctly

**Comment by Auburn** [comment]
On MacOS you will need to set the NoiseTool binary file as executable and run it. On Windows make sure you extract all the zip contents before running the exe or it won't be able to find the FastNoise.dll

**Comment by slit-bodmod** [comment]
ah, I how do you know how to make a file executable, should I find some tutorials?

**Comment by Auburn** [comment]
On the terminal do `chmod +x ./bin/NoiseTool` then you can run it by double clicking the file. You will also need to allow it to run from the "Security and Privacy" system preferences page

**Comment by slit-bodmod** [comment]
ah thankyou very much

**Comment by slit-bodmod** [comment]
It all works fine, I have one question which isn't an issue so I didn't want a new thread but I can if you want. 
Is there any way to instead of generating the mesh based on whether a 3d noise value is below an ISO threshold, just generating it up to a 2d noise value, so you can generate like terrain instead of caves? I know you can do that using offseting it with a Y-axis gradient but that noise will look different than just slicing the 2d noise like in the texture preview

**Comment by Auburn** [comment]
In the debug window you can change the mesh generation to a 2D height map

**Comment by slit-bodmod** [comment]
ah yeah thanks
