### ISSUE TITLE
Grid2D/3D Index lookup?

### ISSUE THREAD

**Issue by iDevelopThings** [Auburn/FastNoise2#86]
I'm honestly not sure if this is a stupid question or not, I've spent way too long trying to figure it out.

If we call:
```
 Generator.Noise.GenUniformGrid3D(
    noise,
    ChunkCoord.x, ChunkCoord.y, ChunkCoord.z,
    chunkSize, chunkSize, chunkSize,
    0.02f,
    Generator.Seed
);
```

How do I go about translating my Chunk's global x,y,z position into the noise key index?

Everything I try seems to end up with some wonky map output

**Comment by Auburn** [comment]
You can see how to index it here: https://github.com/Auburn/FastNoise2/wiki/3:-Getting-started-using-FastNoise2#generate-noise
