### ISSUE TITLE
Are there any plans to release ue4 version?

### ISSUE THREAD

**Issue by anlingbbq** [Auburn/FastNoise2#9]
Hi Jordan Peck, I want to use it in unreal, I tried but I had a lot of problems, Are there any plans to release ue4 version?

**Comment by Auburn** [comment]
You probably want to avoid using UE4s build system to compile the FastNoise2 code, it's possible but not nice to setup. Your best bet is to compile it as a static library outside of UE4 and link it as part of the UE4 build.

**Comment by anlingbbq** [comment]
thank you! I'm now trying to encapsulate the FastNoiseLite to unreal, It's more simple, thanks again, FastNoise is very useful

**Comment by caseymcc** [comment]
I ran into the same, as passing any FastNoise header into the UE4 build fails as the UE4 build is not using the latest versions of the c++ standard. I am including FastNoise through another library so I just hid all the FastNoise includes inside the cpp of the library and used opaque pointers to hide any type usage. If you just want to use FastNoise directly then just encapsulate (I think above you meant incorporate?) FastNoise in a lib and hide the interface with a simpler one.

**Comment by Auburn** [comment]
There could probably be a version of the header that didn't have any modern C++, it would limit you to only creating nodes via the encoded node trees though
