### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by egorodet** [Auburn/FastNoise2#90]
FastNoise nodes can not be created/released simultaneously from multiple threads because it's mechanism relies on a global variable access without thread-safe protection. Creation or release of nodes fails with access violation in different code locations inside library.

**Comment by Auburn** [comment]
Can you show in more detail where the issue is, I've not seen any issues when multi threading node creation. The node allocator should be thread-safe

**Comment by egorodet** [comment]
Every time it crashes in a different place, here's one example:
![image](https://user-images.githubusercontent.com/21955635/177211307-a56d736d-bcee-4547-9ac0-a3e277a262f5.png)
![image](https://user-images.githubusercontent.com/21955635/177211533-c25a1f06-5245-44c7-b5f9-1235056be542.png)

**Comment by egorodet** [comment]
Btw, it starts working when I make node variables `static` inside thread functions.

**Comment by Auburn** [comment]
Hmm, I'm not seeing how that could mess up. I'll probably need to make a test myself to try force it to happen. What is the thread doing so I can replicate the behaviour?

**Comment by caseymcc** [comment]
@egorodet (never used task_flow) but is `t` going to be 0-63? But your noise per thread is only 0-15? In which case you are going to be out of bounds?

**Comment by egorodet** [comment]
Sorry, my mistake. I fixed out-of-bounds access in PR, but it was not the reason of described issue, which is still reproducible. On my machine it reproduces with higher number of threads, i.e. number of iterations in `task_flow.for_each_index(0, N, 1)`.

I'm not sure that it will be possible to use single node for noise generation in all threads, because I need to have different noise parameters for different chunks of data generated by different threads.

**Comment by egorodet** [comment]
Thanks! It seems to be working fine now, so I'm closing this issue.
