### ISSUE TITLE
MacOS ARM build is failing

### ISSUE THREAD

**Issue by egorodet** [Auburn/FastNoise2#93]
FastNoise library build fails on MacOS, see MethaneKit [build log](https://egorodet.visualstudio.com/MethaneKit/_build/results?buildId=1789&view=logs&j=c44f1632-87af-5839-172b-30b58ca5407a&t=790ce908-59e9-55d8-4430-97766a12d5ab) with FastNoise2 integrated and screenshot of Xcode with FastNoise2 build errors:

<img width="1512" alt="Screenshot 2022-07-08 at 17 23 11" src="https://user-images.githubusercontent.com/21955635/178011397-bfa9c7d6-9b51-444f-9cba-112257087112.png">

**Comment by Auburn** [comment]
Hi, there currently is no support for ARM CPUs. I'm guessing you are building on an M1/2 Mac

The feature is on the to-do list

**Comment by egorodet** [comment]
Yes, you're right. I was trying to build for M1. I did not notice that ARM is not supported, it would be better to mention it on README page. Ok, then I'll have to postpone the integration of this library in my project, until ARM CPU support is ready. Is there an issue to track it?

**Comment by Auburn** [comment]
#75

**Comment by Auburn** [comment]
MacOS ARM is supported now
