### ISSUE TITLE
Inconsistent Heightmap 2D preview rendering

### ISSUE THREAD

**Issue by RooTender** [Auburn/FastNoise2#98]
I've found a bug where using generators You can see that for `2D heightmap` rendering behaves... weird. It does **not** apply to `Voxel 3D` preview. I've tried to find the root cause of this problem but found nothing particular.

## Heightmap 2D
![Heightmap 2D](https://user-images.githubusercontent.com/24989290/187232565-168be229-61cc-463a-acd7-76b47b5037dd.png)

**Comment by Auburn** [comment]
This isn't a bug more an artifact of how the heightmap mesh is created. The mesh is created by connecting a grid of vertices together using quads (2 triangles), this ends up looking weird when there is a huge height difference between the quad corners.
