### ISSUE TITLE
`GenSingle2D` method returns wrong values

### ISSUE THREAD

**Issue by RooTender** [Auburn/FastNoise2#99]
# Description
I wanted to generate a 8x8 area of points using `GenSingle2D`. However, I am getting **wrong** results compared to the `GenUniformGrid2D` function.

### `GetNoise` method
```cpp
std::vector<std::vector<float>> Noise2D::GetNoise(const glm::ivec2 origin, const int size) const
{
	auto noise = std::vector<float>(static_cast<unsigned>(size * size));

	const auto x = origin.x * size;
	const auto y = origin.y * size;

	_noiseGenerator->GenUniformGrid2D(
		noise.data(),
		x, y,
		size, size,
		_frequency, _seed);

	return ConvertNoiseFrom1DTo2D(noise, size);
}
```
_The method `ConvertNoiseFrom1DTo2D` just rewrites the 1D vector to the 2D one._

### `GetNoiseAt` method
```cpp
float Noise2D::GetNoiseAt(const glm::ivec2 origin, const int size, const int xOffset, const int yOffset) const
{
	const auto x = static_cast<float>(origin.x * size + xOffset);
	const auto y = static_cast<float>(origin.y * size + yOffset);
	
	return _noiseGenerator->GenSingle2D(x, y, _seed);
}
```

## The test
Here is a small test I wrote, where:
- **noisePlane2D** is a noise generated by using `GenUniformGrid2D`
- **noise2D** is a noise generated by using `GenSingle2D`

```cpp
auto size = 8;
// "AgAAAIA/" is an encoded chessboard pattern from FastNoise2 tool, 69 is seed, 0.02 is frequency
auto noise = Noise2D("AgAAAIA/", 69, 0.02f); 
std::vector<std::vector<float>> noise2D;

auto noisePlane2D = noise.GetNoise(glm::ivec2(0, 0), 8);

noise2D.resize(size);
for (auto x = 0; x < size; ++x)
{
	noise2D[x].resize(size);
	for (auto y = 0; y < size; ++y)
	{
		noise2D[x][y] = noise.GetNoiseAt(glm::ivec2(0, 0), size, x, y);
	}
}
```

## The result
![results](https://user-images.githubusercontent.com/24989290/187615449-b58da76c-4ecf-4b16-8742-463408aeadbf.png)

**Comment by Auburn** [comment]
It looks like you aren't applying your frequency value to GenNoiseSingle, you need to multiply your input position by your frequency which is what GenUniformGrid does internally. 

I should maybe look at changing the interfaces so that all the Gen functions take seed and frequency as arguments for consistency

**Comment by RooTender** [comment]
> It looks like you aren't applying your frequency value to GenNoiseSingle, you need to multiply your input position by your frequency which is what GenUniformGrid does internally.
> 
> I should maybe look at changing the interfaces so that all the Gen functions take seed and frequency as arguments for consistency

Oh, I get it. So yes, it would be great to implement it that way for the sake of consistency. An alternative approach is to expand the documentation, but I think the first approach would be faster. Anyway, thanks for quick reply 😃
